### ISSUE TITLE
LED in frizting schematic appears to be reversed

### ISSUE THREAD

**Issue by fmeschia** [jlecomte/ascom-flat-panel#3]
The LED that represent the LED strip in the Fritzing schematic appears to be reverse-biased. If connected that way, no light would come out.

**Comment by jlecomte** [comment]
Indeed! Thank you for catching this. Fix is on the way :)

**Comment by jlecomte** [comment]
Fixed in https://github.com/jlecomte/ascom-flat-panel/commit/3967d9b0d804235080aa38a7e6543275936aa352
